# Generated by Django 6.1.1 on 2026-10-05 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("food", "0001_initial"),)

    operations = (
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="e-post")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="navn")),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="lagt til"
                    ),
                ),
            ],
            options={
                "verbose_name": "redaktør",
                "verbose_name_plural": "redaktører",
                "ordering": ("email",),
            },
        ),
    )
