# Generated by Django 6.1.1 on 2026-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("food", "0002_editor"),)

    operations = (
        migrations.AddField(
            model_name="recipe",
            name="photo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    )
