# Generated by Django 6.1.1 on 2026-10-05 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("food", "0003_recipe_photo"),)

    operations = (
        migrations.CreateModel(
            name="PhotoRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="tidspunkt"
                    ),
                ),
                ("editor", models.EmailField(blank=True, max_length=254, verbose_name="redaktør")),
                ("provider", models.CharField(max_length=40, verbose_name="leverandør")),
                ("model", models.CharField(blank=True, max_length=200, verbose_name="modell")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("read", "lest"),
                            ("unreadable", "kunne ikke leses"),
                            ("failed", "feil hos leverandøren"),
                        ],
                        max_length=20,
                        verbose_name="resultat",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesing fra bilde",
                "verbose_name_plural": "lesinger fra bilde",
                "ordering": ("-at",),
            },
        ),
    )
