# Generated by Django 6.1.1 on 2026-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("food", "0004_photoread"),)

    operations = (
        migrations.AlterModelOptions(
            name="photoread",
            options={
                "ordering": ("-at",),
                "verbose_name": "lesing med KI",
                "verbose_name_plural": "lesinger med KI",
            },
        ),
        migrations.AddField(
            model_name="photoread",
            name="kind",
            field=models.CharField(
                choices=[("photo", "bilde"), ("text", "tekst")],
                default="photo",
                max_length=10,
                verbose_name="fra",
            ),
        ),
    )
