# Generated by Django 6.1.1 on 2026-10-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("food", "0005_photoread_kind"),)

    operations = (
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="recipes", to="food.tag"),
        ),
    )
